project:
  type: website
  output-dir: docs
  resources:
    - MjMaslow_Official_Master_Resume.pdf
    - General_CL.pdf

website:
  description: "Professional Data Science Portfolio"
  open-graph:
    locale: en_US
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Current Work
        href: current.qmd
      - text: Projects
        href: projects.qmd
      - text: Publications
        href: publications.qmd
      - text: Resume / CV
        href: resume.qmd
      - text: Contact
        href: contact.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/matthew-maslow/

format:
  html:
    theme: vapor
    css: styles.css
